version: "3.8"

services:
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
  redis:
    image: redis/redis-stack
    restart: always
    environment:
      REDIS_ARGS: "--requirepass redis-stack"
    ports:
      - "6379:6379"